config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  broadcasts_to :room
  # after_create_commit -> { broadcast_append_to room }
  # after_destroy_commit -> { broadcast_remove_to room }
  # after_update_commit -> { broadcast_replace_to room }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  broadcasts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[new create]

  def new
    @message = @room.messages.new
  end

  def create
    @message = @room.messages.create!(message_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @room }
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room, notice: "Room was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: "Room was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: "Room was successfully destroyed."
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HotwireSandbox
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all'
    = yield :head

    = turbo_include_tags
    = stimulus_include_tags
  %body
    = yield

app/views/messages/_message.html.haml
%p{ id: dom_id(message) }
  = message.created_at.to_s(:short)
  \|
  = message.content

app/views/messages/create.turbo_stream.haml
-# = turbo_stream.append 'messages', @message
-# Return handled by cable

app/views/messages/new.html.haml
%h1 New Message

= turbo_frame_tag 'new_message', target: '_top' do
  = simple_form_for [@room, @message],
    data: { controller: 'reset_form', action: 'turbo:submit-end->reset_form#reset' } do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

    .form-inputs
      = f.input :content, as: :string

    .form-actions
      = f.button :submit

= link_to 'Back', room_path(@room)

app/views/rooms/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(room) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/rooms/_room.html.haml
%p{ id: dom_id(room) }
  %strong Name:
  = room.name

app/views/rooms/edit.html.haml
%h1 Editing room

= turbo_frame_tag 'room' do
  = render 'form', room: @room

= link_to 'Show', @room
\|
= link_to 'Back', rooms_path

app/views/rooms/index.html.haml
%h1 Listing rooms

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @rooms.each do |room|
      %tr
        %td= room.name
        %td= link_to 'Show', room
        %td= link_to 'Edit', edit_room_path(room)
        %td= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Room', new_room_path

app/views/rooms/new.html.haml
%h1 New room

= render 'form', room: @room

= link_to 'Back', rooms_path

app/views/rooms/show.html.haml
%p#notice= notice

= turbo_stream_from @room

= turbo_frame_tag 'room' do
  = render @room

  %p
    = link_to 'Edit', edit_room_path(@room)
    \|
    = link_to 'Back', rooms_path, data: { 'turbo-frame': '_top' }

%div#messages
  = render @room.messages.order(:id)

= turbo_frame_tag 'new_message', src: new_room_message_path(@room), target: '_top'